const express = require('express')
require('dotenv').config()
const cors = require('cors')
const app = express()
app.use(cors())
app.use(express.json())
app.use(express.urlencoded({ extended: true }))
const homeRouter = require('./src/features/home/router/HomeRouter')
const addTalkRouter = require('./src/features/tech_talk/router/AddTechTalkRouter')
const allTalksRouter = require('./src/features/tech_talk/router/GetAllTalksRouter')
const addAssigneeRouter = require('./src/features/assignees/router/AddAssigneeRouter')
const allAssigneeRouter = require('./src/features/assignees/router/GetAssigneesRouter')

app.use('/',homeRouter)
app.use('/api',addTalkRouter)
app.use('/api',allTalksRouter)
app.use('/api',addAssigneeRouter)
app.use('/api',allAssigneeRouter)
app.listen(process.env.PORT, '0.0.0.0',() => {
    console.log(`App is running on PORT ${process.env.PORT}!`)
})